# -*- coding: utf-8 -*-
"""api.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JxTsdI6bWbDPycKU4i1c_uuJX3kusb4Y
"""

import flask

app = flask.Flask(__name__)
app.config["DEBUG"] = True


@app.route('/', methods=['GET'])
def home():
    return "<h1>Distant Reading Archive</h1><p>This site is a prototype API for distant reading of science fiction novels.</p>"

app.run()